# Generated by Django 4.1.7 on 2023-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=('O', 'Other'), max_length=1),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
