# Generated by Django 4.1.7 on 2023-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_person_gender_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'others')], default='female', max_length=1),
        ),
    ]
